### ISSUE TITLE
Opening Download Properties Causes Crash

### ISSUE THREAD

**Issue by Bobrokus** [hawkeye116477/playnite-legendary-plugin#112]
### Prerequisites

- [X] I've looked through [existing issues](https://github.com/hawkeye116477/playnite-legendary-plugin/issues) to make sure that this bug hasn't been reported before.
- [X] I've read the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines) and know netiquette.

### Playnite version

10.34

### Plugin version

1.10.2

### Legendary Launcher version

0.20.34

### Bug description

Opening Download Properties aka hitting CTRL+P in the Download Manager causes Playnite to crash.

### Relevant log

[playnite.log](https://github.com/user-attachments/files/18141196/playnite.log)

```
15-12 17:29:04.830|INFO |ProgramEntry:App arguments: ''
15-12 17:29:06.579|INFO |PlayniteApplication:Application started from 'C:\Users\bobrokus\scoop\apps\playnite\current'
15-12 17:29:06.937|INFO |ExtensionFactory:Loaded plugin: Battle.net library integration, version 2.21
15-12 17:29:07.009|INFO |ExtensionFactory:Loaded plugin: DKG Theme Modifier, version 2.8.3
15-12 17:29:07.052|INFO |ExtensionFactory:Loaded plugin: Extra Metadata Loader, version 1.80
15-12 17:29:07.105|INFO |ExtensionFactory:Loaded plugin: DuplicateHider, version 3.14.5
15-12 17:29:07.150|INFO |ExtensionFactory:Loaded plugin: ThemeExtras, version 1.4.4
15-12 17:29:07.164|INFO |ExtensionFactory:Loaded plugin: Games Size Calculator, version 1.31
15-12 17:29:07.164|INFO |ExtensionFactory:Loaded plugin: GOG Metadata, version 0.2.1
15-12 17:29:07.183|INFO |ExtensionFactory:Loaded plugin: IGDB metadata provider, version 2.10
15-12 17:29:07.183|INFO |ExtensionFactory:Loaded plugin: IGN Metadata Provider, version 0.3.3
15-12 17:29:07.200|INFO |ExtensionFactory:Loaded plugin: Installation Status Updater, version 2.49
15-12 17:29:07.200|INFO |ExtensionFactory:Loaded plugin: Install Button, version 1.3.1
15-12 17:29:07.244|INFO |ExtensionFactory:Loaded plugin: itch.io library integration, version 2.7
15-12 17:29:07.514|INFO |ExtensionFactory:Loaded plugin: LaunchBox Metadata Provider, version 0.7.3
15-12 17:29:07.514|INFO |ExtensionFactory:Loaded plugin: LauncherMenus, version 1.0.0
15-12 17:29:07.649|INFO |ExtensionFactory:Loaded plugin: Legendary (Epic Games) library integration, version 1.10.2
15-12 17:29:07.649|INFO |ExtensionFactory:Loaded plugin: EA app library integration, version 2.13
15-12 17:29:07.802|INFO |ExtensionFactory:Loaded plugin: IsThereAnyDeal, version 3.2.1
15-12 17:29:07.828|INFO |ExtensionFactory:Loaded plugin: Metadata Local, version 3.0.2
15-12 17:29:07.940|INFO |ExtensionFactory:Loaded plugin: SuccessStory, version 3.4
15-12 17:29:08.185|INFO |ExtensionFactory:Loaded plugin: ThemeModifier, version 3.0.1
15-12 17:29:08.185|INFO |ExtensionFactory:Loaded plugin: Steam Chat, version 1.3
15-12 17:29:08.202|INFO |ExtensionFactory:Loaded plugin: Steam Reviews Viewer, version 2.48
15-12 17:29:08.202|INFO |ExtensionFactory:Loaded plugin: Rockstar Games library integration, version 2.9
15-12 17:29:08.222|INFO |ExtensionFactory:Loaded plugin: GG.deals, version 2.1.1
15-12 17:29:08.243|INFO |ExtensionFactory:Loaded plugin: Splash Screen, version 2.41
15-12 17:29:08.243|INFO |ExtensionFactory:Loaded plugin: SteamGridDB Metadata Provider, version 1.2
15-12 17:29:08.336|INFO |ExtensionFactory:Loaded plugin: Steam library integration, version 2.25
15-12 17:29:08.436|INFO |ExtensionFactory:Loaded plugin: Steam Wishlist Discount Notifier, version 1.36
15-12 17:29:08.443|INFO |ExtensionFactory:Loaded plugin: Steam Shortcuts, version 3.1
15-12 17:29:08.475|INFO |ExtensionFactory:Loaded plugin: Universal Steam Metadata, version 2.17
15-12 17:29:08.499|INFO |ExtensionFactory:Loaded plugin: Ubisoft Connect library integration, version 2.6
15-12 17:29:08.514|INFO |ExtensionFactory:Loaded plugin: Wikipedia Metadata, version 1.7.1
15-12 17:29:08.527|INFO |ExtensionFactory:Loaded plugin: Xbox Metadata Provider, version 0.3.3
15-12 17:29:09.247|INFO |ExtensionFactory:Loaded script extension: C:\Users\bobrokus\scoop\apps\playnite\current\Extensions\Steam_Trailers\SteamTrailers.psm1, version 2.17
15-12 17:29:09.375|DEBUG|WindowFactory:Show window Playnite.DesktopApp.Windows.MainWindowFactory: 9ffd02d3-e6c6-42d8-a56a-f700977edf51
15-12 17:29:09.678|DEBUG|GamesCollectionViewEntry:Reloading collection item view properties.
15-12 17:29:09.731|INFO |GameDatabase:Opening db C:\Users\bobrokus\scoop\apps\playnite\current\library
15-12 17:29:09.731|DEBUG|WindowFactory:Show dialog window Playnite.Windows.ProgressWindowFactory: 09a8b549-a0d0-4d08-9383-305b8388c424
15-12 17:29:09.989|DEBUG|ExecutionTimer:--- Timer 'DatabaseLoadCollections', 253 ms to complete.
15-12 17:29:10.341|INFO |DatabaseStats:Completely recalculating database statistics...
15-12 17:29:10.367|DEBUG|WindowFactory:Closing window Playnite.Windows.ProgressWindowFactory: 09a8b549-a0d0-4d08-9383-305b8388c424, True
15-12 17:29:13.875|INFO |PlayniteApplication:Application 10.34.0.23368 started
15-12 17:29:13.889|INFO |MainViewModelBase:Importing games from Battle.net plugin.
15-12 17:29:15.586|INFO |MainViewModelBase:Importing games from itch.io plugin.
15-12 17:29:15.975|INFO |MainViewModelBase:Importing games from Legendary (Epic) plugin.
15-12 17:29:19.087|INFO |MainViewModelBase:Importing games from EA app plugin.
15-12 17:29:19.719|ERROR|PlayniteApplication:Unhandled exception occured.
System.ArgumentException: The path is not of a legal form.
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetPathRoot(String path)
   at System.IO.DriveInfo..ctor(String driveName)
   at LegendaryLibraryNS.LegendaryDownloadProperties.UpdateSpaceInfo(String path, Double installSizeNumber) in Dev:/playnite-legendary-plugin/src/LegendaryDownloadProperties.xaml.cs:line 183
   at LegendaryLibraryNS.LegendaryDownloadProperties.<LegendaryDownloadPropertiesUC_Loaded>d__12.MoveNext() in Dev:/playnite-legendary-plugin/src/LegendaryDownloadProperties.xaml.cs:line 108
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Window.ShowHelper(Object booleanBox)
   at System.Windows.Window.Show()
   at System.Windows.Window.ShowDialog()
   at LegendaryLibraryNS.LegendaryDownloadManager.DownloadPropertiesBtn_Click(Object sender, RoutedEventArgs e) in Dev:/playnite-legendary-plugin/src/LegendaryDownloadManager.xaml.cs:line 880
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at Playnite.DesktopApp.ProgramEntry.Main(String[] args) in C:\projects\playnite\source\Playnite.DesktopApp\ProgramEntry.cs:line 71
15-12 17:29:19.728|DEBUG|WindowFactory:Show dialog window Playnite.Windows.ExtensionCrashHandlerWindowFactory: d4009344-3bd1-419a-8628-08c605a87997
15-12 17:29:19.807|INFO |MainViewModelBase:Importing games from Rockstar Games plugin.
15-12 17:29:19.835|INFO |MainViewModelBase:Importing games from Steam plugin.
15-12 17:29:20.853|INFO |MainViewModelBase:Importing games from Ubisoft Connect plugin.
15-12 17:29:20.901|INFO |MainViewModelBase:Importing emulated games from Nintendo Switch scanner config.
15-12 17:29:21.441|INFO |GameScanner:Scanning emulated directory D:\emulated-games\nintendo-switch.
15-12 17:29:21.471|INFO |MainViewModelBase:Starting Library Install Size scan
15-12 17:29:21.615|INFO |MainViewModelBase:Finished Library Install Size scan
15-12 17:29:22.635|DEBUG|WindowFactory:Show dialog window Playnite.Windows.ProgressWindowFactory: 4d9bb7a4-5878-46e5-b215-1198898d02dc
15-12 17:29:22.711|DEBUG|WindowFactory:Closing window Playnite.Windows.ProgressWindowFactory: 4d9bb7a4-5878-46e5-b215-1198898d02dc, True
15-12 17:29:22.711|DEBUG|Downloader:Downloading string content from https://www.playnite.link/update/stable/10.34/update.json using System.Text.UTF8Encoding encoding.
15-12 17:29:22.711|DEBUG|WindowFactory:Show dialog window Playnite.Windows.ProgressWindowFactory: b2acd020-5e1f-43c2-aa21-86fcc35cce17
15-12 17:29:22.795|DEBUG|WindowFactory:Closing window Playnite.Windows.ProgressWindowFactory: b2acd020-5e1f-43c2-aa21-86fcc35cce17, True
15-12 17:29:22.811|DEBUG|WindowFactory:Show dialog window Playnite.Windows.ProgressWindowFactory: f4d86b11-bf4a-4ad7-b2c5-34ea696ce4c3
15-12 17:29:22.972|DEBUG|WindowFactory:Closing window Playnite.Windows.ProgressWindowFactory: f4d86b11-bf4a-4ad7-b2c5-34ea696ce4c3, True
15-12 17:29:22.988|DEBUG|WindowFactory:Show dialog window Playnite.Windows.ProgressWindowFactory: 6a7ed88b-ab29-48d3-bc7e-5de74b70572f
15-12 17:29:23.008|DEBUG|WindowFactory:Closing window Playnite.Windows.ProgressWindowFactory: 6a7ed88b-ab29-48d3-bc7e-5de74b70572f, True
15-12 17:29:23.070|DEBUG|Downloader:Downloading string content from https://raw.githubusercontent.com/Jeshibu/PlayniteExtensions/main/manifests/Generic_GamesSizeCalculator.yaml using UTF8 encoding.
15-12 17:29:23.205|DEBUG|Downloader:Downloading string content from https://raw.githubusercontent.com/Jeshibu/PlayniteExtensions/main/manifests/Metadata_GOG.yaml using UTF8 encoding.
15-12 17:29:23.289|DEBUG|Downloader:Downloading string content from https://github.com/JosefNemec/PlayniteExtensions/raw/master/manifests/IGDBMetadata_Builtin.yaml using UTF8 encoding.
15-12 17:29:23.563|DEBUG|Downloader:Downloading string content from https://raw.githubusercontent.com/Jeshibu/PlayniteExtensions/main/manifests/Metadata_IGN.yaml using UTF8 encoding.
15-12 17:29:23.625|DEBUG|Downloader:Downloading string content from https://raw.githubusercontent.com/Jeshibu/PlayniteExtensions/main/manifests/Metadata_LaunchBox.yaml using UTF8 encoding.
15-12 17:29:23.690|DEBUG|Downloader:Downloading string content from https://raw.githubusercontent.com/Lacro59/playnite-metadatalocal-plugin/master/manifest/Lacro59_MetadataLocal.yaml using UTF8 encoding.
15-12 17:29:23.760|DEBUG|Downloader:Downloading string content from https://raw.githubusercontent.com/cooperate/SteamGridDBMetadata/master/Manifests/Installer_Manifest.yaml using UTF8 encoding.
15-12 17:29:23.855|DEBUG|Downloader:Downloading string content from https://github.com/JosefNemec/PlayniteExtensions/raw/master/manifests/Universal_Steam_Metadata.yaml using UTF8 encoding.
15-12 17:29:23.982|DEBUG|Downloader:Downloading string content from https://raw.githubusercontent.com/HerrKnarz/Playnite-Extensions/master/Manifest/HerrKnarz_WikipediaMetadata.yaml using UTF8 encoding.
15-12 17:29:24.215|DEBUG|Downloader:Downloading string content from https://raw.githubusercontent.com/Jeshibu/PlayniteExtensions/main/manifests/Metadata_Xbox.yaml using UTF8 encoding.
15-12 17:29:24.285|DEBUG|Downloader:Downloading string content from https://raw.githubusercontent.com/JosefNemec/PlayniteExtensions/master/manifests/BattlenetLibrary_Builtin.yaml using UTF8 encoding.
15-12 17:29:24.367|DEBUG|Downloader:Downloading string content from https://github.com/JosefNemec/PlayniteExtensions/raw/master/manifests/ItchioLibrary_Builtin.yaml using UTF8 encoding.
15-12 17:29:24.641|DEBUG|Downloader:Downloading string content from https://raw.githubusercontent.com/hawkeye116477/playnite-legendary-plugin/main/installer.yaml using UTF8 encoding.
15-12 17:29:24.716|DEBUG|Downloader:Downloading string content from https://github.com/JosefNemec/PlayniteExtensions/raw/master/manifests/OriginLibrary_Builtin.yaml using UTF8 encoding.
15-12 17:29:24.861|DEBUG|Downloader:Downloading string content from https://github.com/JosefNemec/PlayniteExtensions/raw/master/manifests/Rockstar_Games_Library.yaml using UTF8 encoding.
15-12 17:29:25.115|DEBUG|Downloader:Downloading string content from https://github.com/JosefNemec/PlayniteExtensions/raw/master/manifests/SteamLibrary_Builtin.yaml using UTF8 encoding.
15-12 17:29:25.285|DEBUG|Downloader:Downloading string content from https://github.com/JosefNemec/PlayniteExtensions/raw/master/manifests/UplayLibrary_Builtin.yaml using UTF8 encoding.
15-12 17:29:25.440|DEBUG|Downloader:Downloading string content from https://github.com/davidkgriggs/DKG-Theme-Modifier/raw/main/Manifests/Installer_Manifest.yaml using UTF8 encoding.
15-12 17:29:25.714|DEBUG|Downloader:Downloading string content from https://raw.githubusercontent.com/darklinkpower/PlayniteExtensionsCollection/master/manifests/Generic_ExtraMetadataLoader.yaml using UTF8 encoding.
15-12 17:29:25.805|DEBUG|Downloader:Downloading string content from https://raw.githubusercontent.com/felixkmh/DuplicateHider/master/InstallerManifest/felixkmh_DuplicateHider_Plugin.yaml using UTF8 encoding.
15-12 17:29:25.880|DEBUG|Downloader:Downloading string content from https://github.com/felixkmh/ThemeExtras-for-Playnite/raw/master/InstallerManifest/felixkmh_Extras_Plugin.yaml using UTF8 encoding.
15-12 17:29:26.145|DEBUG|Downloader:Downloading string content from https://raw.githubusercontent.com/darklinkpower/PlayniteExtensionsCollection/master/manifests/Generic_InstallationStatusUpdater.yaml using UTF8 encoding.
15-12 17:29:26.235|DEBUG|Downloader:Downloading string content from https://raw.githubusercontent.com/azuravian/playnite-LocalInstallButton/main/manifests/Generic_InstallButton.yaml using UTF8 encoding.
15-12 17:29:26.307|DEBUG|Downloader:Downloading string content from https://raw.githubusercontent.com/odeyity/Playnite-LauncherMenus-Plugin/main/manifest.yaml using UTF8 encoding.
15-12 17:29:26.378|DEBUG|Downloader:Downloading string content from https://raw.githubusercontent.com/Lacro59/playnite-isthereanydeal-plugin/master/manifest/Lacro59_IsThereAnyDeal.yaml using UTF8 encoding.
15-12 17:29:26.468|DEBUG|Downloader:Downloading string content from https://raw.githubusercontent.com/Lacro59/playnite-successstory-plugin/master/manifest/Lacro59_SuccessStory.yaml using UTF8 encoding.
15-12 17:29:26.558|DEBUG|Downloader:Downloading string content from https://raw.githubusercontent.com/Lacro59/playnite-thememodifier-plugin/master/manifest/Lacro59_ThemeModifier.yaml using UTF8 encoding.
15-12 17:29:26.643|DEBUG|Downloader:Downloading string content from https://raw.githubusercontent.com/uwx/PlayniteSteamChat/master/manifest.yaml using UTF8 encoding.
15-12 17:29:26.717|DEBUG|Downloader:Downloading string content from https://raw.githubusercontent.com/darklinkpower/PlayniteExtensionsCollection/master/manifests/Generic_ReviewViewer.yaml using UTF8 encoding.
15-12 17:29:26.901|DEBUG|Downloader:Downloading string content from https://raw.githubusercontent.com/SparrowBrain/Playnite.GGDeals/main/ci/installer_manifest.yaml using UTF8 encoding.
```	

### Screenshots

![image](https://github.com/user-attachments/assets/44da3d96-7959-4823-94df-84cb6fd5ed1d)

**Comment by hawkeye116477** [comment]
I can't reproduce that.
