### ISSUE TITLE
Error while installing overlay

### ISSUE THREAD

**Issue by darklinkpower** [hawkeye116477/playnite-legendary-plugin#26]
### Plugin's version

1.1.2

### Playnite's version

10.20

### Bug description

The error happened when using pip-installed Legendary. Enabling and configuring a custom launcher path fixed the issue when attempting to install again

### Relevant log

```
[DLManager] INFO:  - Cache usage: 0.00 MiB, active tasks: 0
[DLManager] INFO:  + Download	- 0.00 MiB/s (raw) / 0.00 MiB/s (decompressed)
[DLManager] INFO:  + Disk	- 3.26 MiB/s (write) / 0.00 MiB/s (read)
[DLManager] INFO: Waiting for installation to finish...
[DLManager] INFO: All done! Download manager quitting...
[cli] INFO: Finished downloading, setting up overlay...
[cli] INFO: Updating overlay registry entries from "C:\Program Files (x86)\Epic Games\Epic Online Services\managedArtifacts\98bc04bc842e4906993fd6d6644ffb8d" to "G:\Games\PC\Legendary\.overlay"
Traceback (most recent call last):
  File "c:\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python39\Scripts\legendary.exe\__main__.py", line 7, in <module>
  File "c:\python39\lib\site-packages\legendary\cli.py", line 3086, in main
    cli.manage_eos_overlay(args)
  File "c:\python39\lib\site-packages\legendary\cli.py", line 2348, in manage_eos_overlay
    remove_registry_entries(prefix)
  File "c:\python39\lib\site-packages\legendary\lfs\eos.py", line 134, in remove_registry_entries
    remove_registry_value(HKEY_LOCAL_MACHINE, VULKAN_OVERLAY_KEY, value)
  File "c:\python39\lib\site-packages\legendary\lfs\windows_helpers.py", line 58, in remove_registry_value
    k = winreg.OpenKey(hive, key, reserved=0, access=access)
PermissionError: [WinError 5] Acces Denied

19-10 12:20:19.578|ERROR|LegendaryLibrary#LegendaryDownloadManager:[Legendary] exit code: 1
```

**Comment by hawkeye116477** [comment]
I can't reproduce that. If Legendary really needs more permissions, then I'm afraid that I can't do much about it (https://github.com/Tyrrrz/CliWrap/issues/174#issuecomment-1311061879).

**Comment by hawkeye116477** [comment]
Ok, looks like I found a way to reproduce that. However as I said, I can't do nothing about that. If it EOS was previously saved in some path which only admin can modify or you want to download it to that path, then you need to relaunch Playnite as admin.
