### ISSUE TITLE
Check for games updates seems broken

### ISSUE THREAD

**Issue by ezeholz** [hawkeye116477/playnite-legendary-plugin#48]
### Playnite version

10.32.0.18786

### Plugin version

1.5.0.40296

### Legendary Launcher version

0.20.34

### Bug description

Every time I try to check whether my epic games are up to date, the plugin breaks, giving me a screen and forcing me to reload Playnite entirely.

### Relevant log
```

27-01 12:46:13.685|ERROR|PlayniteApplication:Unhandled exception occured.
System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at LegendaryLibraryNS.LegendaryUpdateController.<CheckGameUpdates>d__2.MoveNext() in C:\Users\Bartek\Documents\git\playnite-legendary-plugin\src\LegendaryGameController.cs:line 426
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LegendaryLibraryNS.LegendaryUpdateController.<CheckAllGamesUpdates>d__3.MoveNext() in C:\Users\Bartek\Documents\git\playnite-legendary-plugin\src\LegendaryGameController.cs:line 473
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LegendaryLibraryNS.LegendaryLibrarySettingsView.<GamesUpdateCheckBtn_Click>d__22.MoveNext() in C:\Users\Bartek\Documents\git\playnite-legendary-plugin\src\LegendaryLibrarySettingsView.xaml.cs:line 564
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Window.ShowHelper(Object booleanBox)
   at System.Windows.Window.Show()
   at System.Windows.Window.ShowDialog()
   at Playnite.Windows.WindowFactory.<>c__DisplayClass16_0.<CreateAndOpenDialog>b__0(Object a) in C:\projects\playnite\source\Playnite\Windows\WindowFactory.cs:line 82
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at System.Windows.Threading.DispatcherSynchronizationContext.Send(SendOrPostCallback d, Object state)
   at Playnite.Windows.WindowFactory.CreateAndOpenDialog(Object dataContext) in C:\projects\playnite\source\Playnite\Windows\WindowFactory.cs:line 57
   at Playnite.DesktopApp.ViewModels.DesktopAppViewModel.<InitializeCommands>b__323_48(Object a) in C:\projects\playnite\source\Playnite.DesktopApp\ViewModels\DesktopAppViewModel_Commands.cs:line 351
   at Playnite.SDK.RelayCommand`1.Execute(Object parameter) in C:\projects\playnite\source\PlayniteSDK\RelayCommand.cs:line 205
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at Playnite.DesktopApp.ProgramEntry.Main(String[] args) in C:\projects\playnite\source\Playnite.DesktopApp\ProgramEntry.cs:line 71

```
### Screenshots

![image](https://github.com/hawkeye116477/playnite-legendary-plugin/assets/30635862/481b9b3d-7f0c-4f8f-b6c1-3490a7425773)

**Comment by ezeholz** [comment]
According to the line 426 of the said file, it's checking whether my DLCs have updates. I currently have one DLC installed:

![image](https://github.com/hawkeye116477/playnite-legendary-plugin/assets/30635862/b41039d9-752b-4113-b058-8e4b6cb8b67d)

**Comment by hawkeye116477** [comment]
Hmm, I checked and seems that everything is fine. However if it's really that line, then looks like problem might be that somehow you received broken manifest because of your problems with Internet or maybe disk. I can add few more null checks, but if it's really something on your side and not something bad on Epic's side, then it will be only partially fine.
Did you tried to clear cache?

**Comment by ezeholz** [comment]
I just did, same issue. FYI, I had some broken manifests showing up over legendary cli, but I was able to remove the check of those from `/ProgramData/Epic/EpicGamesLauncher/Data/Manifests`

I might try to uninstall Alien DLC, to check if the other one it's detected correctly. Would that work?

**Comment by hawkeye116477** [comment]
> /ProgramData/Epic/EpicGamesLauncher/Data/Manifests

I mean those from `C:\Users\User\.config\legendary\metadata` and `%APPDATA%\Playnite\ExtensionsData\ead65c3b-2f8f-4e37-b4e6-b3de6be540c6\infocache`.

**Comment by hawkeye116477** [comment]
[LegendaryLibrary_1_5_0_f1.zip](https://github.com/hawkeye116477/playnite-legendary-plugin/files/14073131/LegendaryLibrary_1_5_0_f1.zip)

Can you rename zip to pext and drag and drop it to Playnite to install and check if it fixes that?

**Comment by ezeholz** [comment]
I did, that seems to solve the issue.
I really don't know why that's happening, maybe some old files from EGS.
![image](https://github.com/hawkeye116477/playnite-legendary-plugin/assets/30635862/b35211fd-f53f-4094-b43c-7a97bccb546e)

**Comment by hawkeye116477** [comment]
Well, if you already cleared cache from Plugin's settings, then legendary should rather download new files. However maybe it's indeed some issue with that `egl-sync` command or disk or something weird at Epic servers, cuz looks like one or more DLCs doesn't contain IDs. Anyway, that's good that my solution was helpful.
