### ISSUE TITLE
Crash while troubleshooting failing install.

### ISSUE THREAD

**Issue by SkyNinja** [hawkeye116477/playnite-legendary-plugin#84]
### Prerequisites

- [x] I've looked through [existing issues](https://github.com/hawkeye116477/playnite-legendary-plugin/issues) to make sure that this bug hasn't been reported before.
- [X] I've read the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines) and know netiquette.

### Playnite version

10.34

### Plugin version

1.9.0

### Legendary Launcher version

0.20.34

### Bug description

Upon trying to install Darkest Dungeon, the game was set to 'Queued' but never started downloading. I cancelled and tried again, and the same thing happened. When I pressed the button in the plugin settings to open the appdata folder, the folder opened, followed by Playnite immediately crashing.

I installed via Legendary directly after the crash with no problem. Once I had reopened Playnite, I installed another game via the plugin with no problem. I then uninstalled via playnite successfully, restarted and attempted to install again. This time it worked with seemingly no issue.

So far, I can't recreate the crash.

### Relevant log

playnite.log
```
13-09 05:56:40.407|ERROR|PlayniteApplication:Unhandled exception occured.
System.NullReferenceException: Object reference not set to an instance of an object.
   at LegendaryLibraryNS.LegendaryDownloadManager.<Install>d__16.MoveNext() in Dev:/playnite-legendary-plugin/src/LegendaryDownloadManager.xaml.cs:line 338
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at LegendaryLibraryNS.LegendaryDownloadManager.<Install>d__16.MoveNext() in Dev:/playnite-legendary-plugin/src/LegendaryDownloadManager.xaml.cs:line 333
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LegendaryLibraryNS.LegendaryDownloadManager.<DoNextJobInQueue>d__12.MoveNext() in Dev:/playnite-legendary-plugin/src/LegendaryDownloadManager.xaml.cs:line 153
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Window.ShowHelper(Object booleanBox)
   at System.Windows.Window.Show()
   at System.Windows.Window.ShowDialog()
   at Playnite.Windows.WindowFactory.<>c__DisplayClass16_0.<CreateAndOpenDialog>b__0(Object a) in C:\projects\playnite\source\Playnite\Windows\WindowFactory.cs:line 82
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at System.Windows.Threading.DispatcherSynchronizationContext.Send(SendOrPostCallback d, Object state)
   at Playnite.Windows.WindowFactory.CreateAndOpenDialog(Object dataContext) in C:\projects\playnite\source\Playnite\Windows\WindowFactory.cs:line 57
   at Playnite.DesktopApp.ViewModels.DesktopAppViewModel.<InitializeCommands>b__323_48(Object a) in C:\projects\playnite\source\Playnite.DesktopApp\ViewModels\DesktopAppViewModel_Commands.cs:line 351
   at Playnite.SDK.RelayCommand`1.Execute(Object parameter) in C:\projects\playnite\source\PlayniteSDK\RelayCommand.cs:line 205
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at Playnite.DesktopApp.ProgramEntry.Main(String[] args) in C:\projects\playnite\source\Playnite.DesktopApp\ProgramEntry.cs:line 71
13-09 05:56:40.472|DEBUG|WindowFactory:Show dialog window Playnite.Windows.ExtensionCrashHandlerWindowFactory: ae2d67af-e555-4d2b-a61b-b327db6810b4
```

extensions.log:
```
13-09 05:20:12.872|DEBUG|Extras#ThemeExtras:Pushed "Details View - Darkest Dungeon"
13-09 05:44:50.367|DEBUG|LegendaryLibrary#CliWrapCommandExtensions:Executing command: C:\Users\payna\AppData\Local\Microsoft\WinGet\Links\legendary.exe info 36cbf259e631478eaac6ea244e55a709 --json
13-09 05:45:21.903|DEBUG|Extras#ThemeExtras:Pushed "Legendary Panel"
13-09 05:49:06.468|DEBUG|Extras#ThemeExtras:Pushed "Details View - Darkest Dungeon"
13-09 05:49:29.061|DEBUG|Extras#ThemeExtras:Pushed "Legendary Panel"
13-09 05:50:19.487|DEBUG|LegendaryLibrary#CliWrapCommandExtensions:Executing command: C:\Users\payna\AppData\Local\Microsoft\WinGet\Links\legendary.exe -V
13-09 05:55:30.626|DEBUG|LegendaryLibrary#CliWrapCommandExtensions:Executing command: C:\Users\payna\AppData\Local\Microsoft\WinGet\Links\legendary.exe -V
13-09 05:55:34.427|DEBUG|LegendaryLibrary#ProcessStarter:Starting process: explorer.exe, C:\Users\payna\AppData\Roaming\Playnite, , False
13-09 05:56:40.357|DEBUG|LegendaryLibrary#CliWrapCommandExtensions:Executing command: C:\Users\payna\AppData\Local\Microsoft\WinGet\Links\legendary.exe -y install 36cbf259e631478eaac6ea244e55a709 --base-path D:\Games\Legendary --skip-dlcs
13-09 05:56:40.552|DEBUG|LegendaryLibrary#CliWrapCommandExtensions:Executing command: C:\Users\payna\AppData\Local\Microsoft\WinGet\Links\legendary.exe -y install 36cbf259e631478eaac6ea244e55a709 --base-path D:\Games\Legendary --skip-dlcs
```

**Comment by hawkeye116477** [comment]
> the game was set to 'Queued' but never started downloading. I cancelled and tried again, and the same thing happened. 

That can happen if there is file with `.lock` extension at config path of Legendary.  Legendary doesn't allow to run multiple instances, so leaves that file and removes it after it closes. So plugin waits when Legendary will clean up. 
In case of crash, I'll see later what can be done.

**Comment by SkyNinja** [comment]
> So plugin waits when Legendary will clean up. 

I'm confused by this, does this mean that the "LegendaryLibrary#CliWrapCommandExtensions:Executing command:" lines in extensions.log don't necessarily mean the command has _actually_ been executed?

**Comment by hawkeye116477** [comment]
> don't necessarily mean the command has actually been executed?

Yeah, it's always executed when its mentioned. When it's executed, status should be also "running". So in that case I was wrong and cause is different.

**Comment by hawkeye116477** [comment]
I added few fixes recently, but I'm not sure if that solves that, cuz I can't reproduce that. Let me know again if that will repeat.
